### ISSUE TITLE
来给你2015年那篇设计博客点个赞

### ISSUE THREAD

**Issue by 1c7** [Aaron-zheng/sightcorner#1]
http://www.sightcorner.com/technique/2015_01_04

在谷歌搜 Sketch 教程之类的翻了好几页看到的。加油啊~最近还有搞 Sketch 吗？
刚开始看你的博客首页，感觉很丰富的样子，到处旅游啊。
赞

**Comment by 1c7** [comment]
![image](https://cloud.githubusercontent.com/assets/1804755/25239264/1e25f6f8-2622-11e7-98aa-2a8dc5f2755c.png)
咦？！
我们团队在5楼。（2016年12月入驻的）（包括我就2个人哈哈哈）

**Comment by 1c7** [comment]
![image](https://cloud.githubusercontent.com/assets/1804755/25239656/2b96eda0-2623-11e7-9796-247796b8353b.png)

那边现在有个卡。

**Comment by aaronzhengfc** [comment]
哈哈哈，最近没搞  sketch 啦，都是业余的时候玩一下。

好厉害，进驻了 羊城同创汇。

**Comment by 1c7** [comment]
看到打工旅行第26周了。慢慢看。
